apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-kubernetes-agent

configMapGenerator:
  - name: initscripts
    files:
      - init-scripts/hello-world.sh

resources:
 - namespace.yaml
 - sts.yaml
 - secret.yaml